# Generated by Django 4.2.3 on 2023-08-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artist',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='release_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
